=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/bda_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"description": "A purchase order document from Cycle City to a customer",
	"class": "Purchase Order",
	"type": "object",
	"definitions": {
		"OrderItem": {
			"type": "object",
			"properties": {
				"sku": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The stock keeping unit of the item"
				},
				"product_name": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The name of the product"
				},
				"description": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "A detailed description of the product"
				},
				"quantity": {
					"type": "number",
					"inferenceType": "explicit",
					"instruction": "The quantity of the product ordered"
				},
				"unit_price": {
					"type": "number",
					"inferenceType": "explicit",
					"instruction": "The unit price of the product"
				},
				"line_total": {
					"type": "number",
					"inferenceType": "explicit",
					"instruction": "The total price for the line item"
				},
				"option_color": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The color option of the product"
				},
				"option_size": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The size option of the product"
				},
				"option_weight": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The weight option of the product"
				},
				"option_battery": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The battery option of the product"
				},
				"option_range": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The range option of the product"
				},
				"option_speed": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The speed option of the product"
				},
				"option_wheel_size": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The wheel size option of the product"
				},
				"option_brake_type": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The brake type option of the product"
				},
				"option_certification": {
					"type": "string",
					"inferenceType": "explicit",
					"instruction": "The certification option of the product"
				}
			}
		}
	},
	"properties": {
		"po_number": {
			"type": "string",
			"inferenceType": "explicit",
			"instruction": "The unique identifier for the purchase order"
		},
		"retailer_name": {
			"type": "string",
			"inferenceType": "explicit",
			"instruction": "The name of the retailer"
		},
		"order_date": {
			"type": "string",
			"inferenceType": "explicit",
			"instruction": "The date when the order was placed"
		},
		"order_total": {
			"type": "number",
			"inferenceType": "explicit",
			"instruction": "The total amount for the order"
		},
		"customer_name": {
			"type": "string",
			"inferenceType": "inferred",
			"instruction": "The name of the customer"
		},
		"special_requests": {
			"type": "string",
			"inferenceType": "inferred",
			"instruction": "Any special requests or notes included in the order"
		},
		"order_items": {
			"type": "array",
			"instruction": "A list of all items ordered",
			"items": {
				"$ref": "#/definitions/OrderItem"
			}
		}
	}
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-006_Trail_Riders_ground_truth.json
{
  "po_number": "PO-2026-0224-4485",
  "retailer_name": "Trail Riders",
  "order_date": "2026-02-24",
  "order_total": 50667.16,
  "customer_name": "Joshua Green",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-EB-075",
      "product_name": "E-Flow Elite",
      "description": "E-Flow Elite",
      "quantity": 6,
      "unit_price": 2837.05,
      "line_total": 17022.30,
      "option_color": "gr5432",
      "option_size": "XS",
      "option_weight": "17.0 lbs",
      "option_battery": "48V 17.5Ah",
      "option_range": "35 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-KB-032",
      "product_name": "Tiny Elite",
      "description": "Tiny Elite",
      "quantity": 2,
      "unit_price": 664.65,
      "line_total": 1329.30,
      "option_color": "bl4567",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-054",
      "product_name": "E-Ride Pro",
      "description": "E-Ride Pro",
      "quantity": 4,
      "unit_price": 4612.95,
      "line_total": 18451.80,
      "option_color": "wh9001",
      "option_size": "XS",
      "option_weight": "23.2 lbs",
      "option_battery": "36V 12Ah",
      "option_range": "41 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-HB-044",
      "product_name": "Handlebar Master",
      "description": "Handlebar Master",
      "quantity": 1,
      "unit_price": 118.09,
      "line_total": 118.09,
      "option_color": "sv3456",
      "option_size": "L",
      "option_weight": "20.4 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-RB-075",
      "product_name": "Aero Master",
      "description": "Aero Master",
      "quantity": 4,
      "unit_price": 776.82,
      "line_total": 3107.28,
      "option_color": "cr4321",
      "option_size": "XS",
      "option_weight": "29.9 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MB-044",
      "product_name": "Peak Sport",
      "description": "Peak Sport",
      "quantity": 1,
      "unit_price": 1793.54,
      "line_total": 1793.54,
      "option_color": "bl4567",
      "option_size": "XS",
      "option_weight": "33.0 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-GR-013",
      "product_name": "Precision Derailleur",
      "description": "Precision Derailleur",
      "quantity": 5,
      "unit_price": 162.59,
      "line_total": 812.95,
      "option_color": "cr4321",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "7",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-049",
      "product_name": "E-Ride Deluxe",
      "description": "E-Ride Deluxe",
      "quantity": 3,
      "unit_price": 2255.93,
      "line_total": 6767.79,
      "option_color": "bk1798",
      "option_size": "M",
      "option_weight": "30.7 lbs",
      "option_battery": "48V 14Ah",
      "option_range": "29 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-CP-014",
      "product_name": "Heavy-Duty Kit",
      "description": "Heavy-Duty Kit",
      "quantity": 3,
      "unit_price": 421.37,
      "line_total": 1264.11,
      "option_color": "ol4567",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-011_Wheels__More_ground_truth.json
{
  "po_number": "PO-2026-0224-7702",
  "retailer_name": "Wheels & More",
  "order_date": "2026-02-24",
  "order_total": 14713.97,
  "customer_name": "Ronald Nguyen",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-FR-034",
      "product_name": "Durable Chassis",
      "description": "Durable Chassis",
      "quantity": 8,
      "unit_price": 979.50,
      "line_total": 7836.00,
      "option_color": "ti2345",
      "option_size": "XS",
      "option_weight": "29.4 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-KB-001",
      "product_name": "Little Deluxe",
      "description": "Little Deluxe",
      "quantity": 7,
      "unit_price": 700.06,
      "line_total": 4900.42,
      "option_color": "yl5678",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MT-005",
      "product_name": "Lightweight Tool",
      "description": "Lightweight Tool",
      "quantity": 2,
      "unit_price": 64.45,
      "line_total": 128.90,
      "option_color": "",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-CP-007",
      "product_name": "Heavy-Duty Component",
      "description": "Heavy-Duty Component",
      "quantity": 5,
      "unit_price": 369.73,
      "line_total": 1848.65,
      "option_color": "br7654",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-005_Speed_Shop_ground_truth.json
{
  "po_number": "PO-2026-0224-1901",
  "retailer_name": "Speed Shop",
  "order_date": "2026-02-24",
  "order_total": 26272.41,
  "customer_name": "William Moore",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-MB-071",
      "product_name": "Canyon Sport",
      "description": "Canyon Sport",
      "quantity": 6,
      "unit_price": 1716.95,
      "line_total": 10301.70,
      "option_color": "ti2345",
      "option_size": "M",
      "option_weight": "24.3 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-ST-012",
      "product_name": "High-Performance Seat",
      "description": "High-Performance Seat",
      "quantity": 2,
      "unit_price": 181.59,
      "line_total": 363.18,
      "option_color": "or8901",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-076",
      "product_name": "E-Drive Sport",
      "description": "E-Drive Sport",
      "quantity": 1,
      "unit_price": 6342.08,
      "line_total": 6342.08,
      "option_color": "ti2345",
      "option_size": "L",
      "option_weight": "16.3 lbs",
      "option_battery": "48V 17.5Ah",
      "option_range": "30 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-CH-039",
      "product_name": "High-Performance Drive",
      "description": "High-Performance Drive",
      "quantity": 3,
      "unit_price": 19.56,
      "line_total": 58.68,
      "option_color": "",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MT-004",
      "product_name": "Durable Tool",
      "description": "Durable Tool",
      "quantity": 1,
      "unit_price": 55.32,
      "line_total": 55.32,
      "option_color": "",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-SF-023",
      "product_name": "High-Performance Vest",
      "description": "High-Performance Vest",
      "quantity": 5,
      "unit_price": 58.40,
      "line_total": 292.00,
      "option_color": "sv3456",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-079",
      "product_name": "E-Force Classic",
      "description": "E-Force Classic",
      "quantity": 3,
      "unit_price": 2953.15,
      "line_total": 8859.45,
      "option_color": "sv3456",
      "option_size": "M",
      "option_weight": "34.3 lbs",
      "option_battery": "48V 14Ah",
      "option_range": "47 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-008_Adventure_Cycling_ground_truth.json
{
  "po_number": "PO-2026-0224-6043",
  "retailer_name": "Adventure Cycling",
  "order_date": "2026-02-24",
  "order_total": 13620.38,
  "customer_name": "Sarah Mitchell",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-MB-039",
      "product_name": "Boulder Classic",
      "description": "Boulder Classic",
      "quantity": 2,
      "unit_price": 2803.47,
      "line_total": 5606.94,
      "option_color": "gy6789",
      "option_size": "XL",
      "option_weight": "16.6 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-RB-041",
      "product_name": "Turbo Pro",
      "description": "Turbo Pro",
      "quantity": 4,
      "unit_price": 2003.36,
      "line_total": 8013.44,
      "option_color": "ol4567",
      "option_size": "L",
      "option_weight": "27.9 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-007_City_Bikes_Plus_ground_truth.json
{
  "po_number": "PO-2026-0224-7969",
  "retailer_name": "City Bikes Plus",
  "order_date": "2026-02-24",
  "order_total": 66129.79,
  "customer_name": "Jeffrey Evans",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-MB-051",
      "product_name": "Alpine Deluxe",
      "description": "Alpine Deluxe",
      "quantity": 4,
      "unit_price": 764.47,
      "line_total": 3057.88,
      "option_color": "gr5432",
      "option_size": "M",
      "option_weight": "18.2 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-045",
      "product_name": "E-Drive Pro",
      "description": "E-Drive Pro",
      "quantity": 6,
      "unit_price": 4819.41,
      "line_total": 28916.46,
      "option_color": "br7654",
      "option_size": "M",
      "option_weight": "31.8 lbs",
      "option_battery": "48V 14Ah",
      "option_range": "34 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-FR-019",
      "product_name": "Durable Base",
      "description": "Durable Base",
      "quantity": 5,
      "unit_price": 281.91,
      "line_total": 1409.55,
      "option_color": "bl4567",
      "option_size": "XS",
      "option_weight": "19.1 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-HB-008",
      "product_name": "Bar Sport",
      "description": "Bar Sport",
      "quantity": 5,
      "unit_price": 43.14,
      "line_total": 215.70,
      "option_color": "bl4567",
      "option_size": "L",
      "option_weight": "24.2 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MB-073",
      "product_name": "Terrain Master",
      "description": "Terrain Master",
      "quantity": 7,
      "unit_price": 3372.52,
      "line_total": 23607.64,
      "option_color": "cr4321",
      "option_size": "XL",
      "option_weight": "23.9 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-EB-061",
      "product_name": "E-Drive Sport",
      "description": "E-Drive Sport",
      "quantity": 3,
      "unit_price": 2391.02,
      "line_total": 7173.06,
      "option_color": "br7654",
      "option_size": "XL",
      "option_weight": "18.9 lbs",
      "option_battery": "36V 12Ah",
      "option_range": "59 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MB-022",
      "product_name": "Trail Classic",
      "description": "Trail Classic",
      "quantity": 2,
      "unit_price": 848.96,
      "line_total": 1697.92,
      "option_color": "sv3456",
      "option_size": "S",
      "option_weight": "23.8 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-MT-029",
      "product_name": "Precision Cleaner",
      "description": "Precision Cleaner",
      "quantity": 2,
      "unit_price": 25.79,
      "line_total": 51.58,
      "option_color": "",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-003_Mountain_Gear_Co_ground_truth.json
{
  "po_number": "PO-2026-0224-0524",
  "retailer_name": "Mountain Gear Co",
  "order_date": "2026-02-24",
  "order_total": 9745.53,
  "customer_name": "John Hall",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-EB-017",
      "product_name": "E-Ride Master",
      "description": "E-Ride Master",
      "quantity": 5,
      "unit_price": 1860.69,
      "line_total": 9303.45,
      "option_color": "cb8901",
      "option_size": "S",
      "option_weight": "19.4 lbs",
      "option_battery": "48V 17.5Ah",
      "option_range": "41 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-KB-033",
      "product_name": "Small Classic",
      "description": "Small Classic",
      "quantity": 2,
      "unit_price": 221.04,
      "line_total": 442.08,
      "option_color": "ol4567",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}

=== awscordsen/sample-blueprint-optimizer-for-data-automation/workshop/sample_data/purchase_order/PO_RT-014_Two_Wheel_Store_ground_truth.json
{
  "po_number": "PO-2026-0224-4497",
  "retailer_name": "Two Wheel Store",
  "order_date": "2026-02-24",
  "order_total": 37972.01,
  "customer_name": "Jessica Hernandez",
  "special_requests": "",
  "order_items": [
    {
      "sku": "AB-EB-014",
      "product_name": "E-Power Elite",
      "description": "E-Power Elite",
      "quantity": 3,
      "unit_price": 2025.11,
      "line_total": 6075.33,
      "option_color": "bl4567",
      "option_size": "M",
      "option_weight": "31.5 lbs",
      "option_battery": "48V 14Ah",
      "option_range": "48 miles",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-SF-036",
      "product_name": "Advanced Guard",
      "description": "Advanced Guard",
      "quantity": 6,
      "unit_price": 75.54,
      "line_total": 453.24,
      "option_color": "br7654",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-CH-014",
      "product_name": "Heavy-Duty Link",
      "description": "Heavy-Duty Link",
      "quantity": 4,
      "unit_price": 33.46,
      "line_total": 133.84,
      "option_color": "",
      "option_size": "",
      "option_weight": "",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    },
    {
      "sku": "AB-RB-040",
      "product_name": "Lightning Classic",
      "description": "Lightning Classic",
      "quantity": 8,
      "unit_price": 3913.70,
      "line_total": 31309.60,
      "option_color": "gy6789",
      "option_size": "S",
      "option_weight": "20.5 lbs",
      "option_battery": "",
      "option_range": "",
      "option_speed": "",
      "option_wheel_size": "",
      "option_brake_type": "",
      "option_certification": ""
    }
  ]
}
